### ISSUE TITLE
Support for CVRP

### ISSUE THREAD

**Issue by wouterkool** [N-Wouda/PyVRP#48]
We would like to support CVRP without time windows. This is currently possible as a special case but inefficient due to unnecessary TWData checks. We should see if we can have a special entrypoint function that avoids doing these checks.

**Comment by leonlan** [comment]
I'm going to benchmark on the X-instances.
- [Vidal (2020)](https://arxiv.org/pdf/2012.10384.pdf) time limit is set at $T_{\max} = n \times 240/100$ seconds
- I'll compute the average distance & avg. relative gap w.r.t. BKS

**Comment by leonlan** [comment]
Results are in.
- The avg. distance of HGS is `63583`.
- The avg. distance in BKS is `63107`.
- That's 0.75% more in terms of distance. 
- The average relative gap is 0.66%. For reference, HGS by Vidal has a 0.11% average relative gap.

Not too bad, considering that this implementation still includes the time window stuff in local search.

If we can get about 0.20% gap then that'd be a great achievement, since most state-of-the-art algorithms are in that range (SISR, FILO, HGS-2012).

I also ran another benchmark with 2x time limits to mimic a situation where we get 2x more iterations. We then get a 0.55% avg. gap. 

The gaps are the largest on the large instances. I think that our algorithm are overfitted for small instances, which is something we also observe on the VRPTW instances.

**Comment by leonlan** [comment]
Some differences between our HGS-CVRP and our version:
- Our code is specialized for VRPTW (obvious).
- HGS-CVRP uses OX-SPLIT. We use SREX, which is not used on CVRP before as far as I know.
- HGS-CVRP uses polar-coordinate based route operators at each LS iteration, after exhausting all node operator moves. We use route operators only when a new best solution is found and apply it to all route pairs (U, V).
	- Vidal (2020) claims that SWAP* is the reason why HGS-CVRP is better than HGS-2012 (0.10% gap vs. 0.20% gap).

I think these three differences directly relate to modification that we can try out to improve performance on CVRP instances.

**Comment by N-Wouda** [comment]
I'm working on the TW stuff in #91.

**Comment by N-Wouda** [comment]
#91 introduced a problem mode `-Dproblem=<type>` that can be used to compile the C++ codebase for different problem types, particularly the `CVRP`. That's already been used to shortcut some of the time window calculations, but more can probably be done to further speed up CVRP.

We should probably profile more extensively and shortcut a few more computations. We might also need to change some logic in the case of CVRP (vs. VRPTW), but those changes are a bit more involved.

**Comment by leonlan** [comment]
The CVRP performance dropped: in https://github.com/N-Wouda/PyVRP/tree/old-cvrp we get an average of 0.28% on X-instances, whereas now we only get about 0.35% (to be confirmed) with the same configuration. It's unclear how this happened. 

I propose the following todos:
- Run DIMACS version on CVRP instances with modified time windows -- our VRPTW solver now does roughly the same as the DIMACS version so it's good to get a rough identification on how that version performs on CVRP.
- Re-implement CVRP specific operators:
	- OX-SPLIT
	- symmetric broken pairs
	- LS operators #99 
- It's also good to sanity check whether the same neighbourhoods are computed. This has the highest priority and should be the easiest to do.

**Comment by N-Wouda** [comment]
> The CVRP performance dropped: in https://github.com/N-Wouda/PyVRP/tree/old-cvrp we get an average of 0.28% on X-instances, whereas now we only get about 0.35% (to be confirmed) with the same configuration. It's unclear how this happened.

This turned out not to be the case. We get about ~0.22% with CVRP-specific parameter settings. @leonlan do you still want to do all the proposed modifications (including #99), or is 0.22% good enough? Particularly #99 seems like a lot of work for very little gain.

**Comment by leonlan** [comment]
> > The CVRP performance dropped: in https://github.com/N-Wouda/PyVRP/tree/old-cvrp we get an average of 0.28% on X-instances, whereas now we only get about 0.35% (to be confirmed) with the same configuration. It's unclear how this happened.
> 
> This turned out not to be the case. We get about ~0.22% with CVRP-specific parameter settings. @leonlan do you still want to do all the proposed modifications (including #99), or is 0.22% good enough? Particularly #99 seems like a lot of work for very little gain.

I kind of want to push the performance closer to HGS-CVRP. PyVRP will then really match the ‘state-of-the-art’ in terms of performance. I’ll focus on the OX-SPLIT things first and keep #99 open for now. This issue on the other hand may be closed, since we have a CVRP specific compilation, and we can have #132 to address the high-level, CVRP-specific solver.
